pipeline:
  build:
    image: node:alpine
    commands:
      - yarn

  test:
    image: node:alpine
    commands:
      - yarn test
  pre-release:
    image: node:alpine
    commands:
      - yarn build
      - tar -zcvf build.tar.gz -C build .
    when:
      event: tag

  release:
    image: plugins/github-release
    files: build.tar.gz
    when:
      event: tag
    secrets: [ github_token ]
  slack:
    image: plugins/slack
    webhook:  <slack_webhook>
    channel: lenapalmçacalme
    username: Jean-Marie-Lepen
    icon_url: https://files.newsnetz.ch/story/2/1/2/21249533/6/topelement.jpg
    secrets: [ slack_webhook ]
    template: >
      {{#success build.status}}
        build {{build.number}} Réussit ! Bravo tu fais avancer la france nest ce pas !
      {{else}}
        build {{build.number}} Tu as échoué ! Tu me déçoit mon petit farfadet :D !
      {{/success}}